### ISSUE TITLE
抖音解析失败

### ISSUE THREAD

**Issue by king6207** [5ime/images_spider#11]
”https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=“这个V1接口好像失效了，抖音可能关闭了这个接口
提示blocked

**Comment by victorymakes** [comment]
返回的只有封面和音乐。没有图集地址。

**Comment by 5ime** [comment]
图集解析没有封面和音乐呀，你是不是请求错了

**Comment by victorymakes** [comment]
不好意思。弄错了。
使用 https://lab.5ime.cn/video 这个网页的时候忘记切换菜单了。以为会自动识别。
